package edu.bjtu.android.entity;

import java.io.Serializable;

public class UserCourse implements Serializable {

        private String user_id;
        private String course_id;
        private String attendtime;

        private static final long serialVersionUID = 1L;

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column course.id
         * @return  the value of course.id
         * @mbg.generated
         */
        public String getUser_id() {
            return user_id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column course.id
         * @param uid  the value for course.id
         * @mbg.generated
         */
        public void setUser_id(String uid) {
            this.user_id = uid == null ? null : uid.trim();
        }

        /**
         * This method was generated by MyBatis Generator. This method returns the value of the database column course.name
         * @return  the value of course.name
         * @mbg.generated
         */
        public String getCourse_id() {
            return course_id;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column course.name
         * @param cid  the value for course.name
         * @mbg.generated
         */
        public void setCourse_id(String cid) {
            this.course_id = cid == null ? null : cid.trim();
        }

        public String getAttendtime() {
            return attendtime;
        }

        /**
         * This method was generated by MyBatis Generator. This method sets the value of the database column course.code
         * @param attendtime the value for course.code
         * @mbg.generated
         */
        public void setAttendtime(String attendtime) {
            this.attendtime = attendtime== null ? null : attendtime.trim();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getClass().getSimpleName());
            sb.append(" [");
            sb.append("Hash = ").append(hashCode());
            sb.append(", user_id=").append(user_id);
            sb.append(", course_id=").append(course_id);
            sb.append(", attendtime=").append(attendtime);
            sb.append(", serialVersionUID=").append(serialVersionUID);
            sb.append("]");
            return sb.toString();
        }
}
