package edu.bjtu.android.dao;

import edu.bjtu.android.entity.Course;
import java.util.List;

import edu.bjtu.android.entity.User;
import edu.bjtu.android.entity.UserCourse;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    int insert(String name, String password, String email, String mobile, String level);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    //List<Course> selectMy();
    //List<UserCourse> selectMy();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}
